### ISSUE TITLE
[Bug]: Klipper pressure_,advance stops working after 3MS install

### ISSUE THREAD

**Issue by deemax-real** [3DCoded/3MS#28] opened 2024-11-09 14:35 UTC
### What happened?

Hi, after 3MS install Klipper pressure advance have mo impact on the print. Pressure advance and smooth time windows disappeared from mainsail gui and even gcode pressure advance have no impact on print (round corners). Also extruder acceleration from printer.cfg stops working (now extruder works with same ACC as axes). Can provide logs before and after 3MS installation if needed.

### Klippy Log

Z

**Comment by deemax-real** [comment] 2024-11-09 17:46
[config-20241109-174017.zip](https://github.com/user-attachments/files/17688828/config-20241109-174017.zip)
[klippy.log](https://github.com/user-attachments/files/17688829/klippy.log)

3ms controller steppers.cfg are for Ender 4.2.2 motherobard under btt_skr_mini_e3_v2

**Comment by 3DCoded** [comment] 2024-11-09 18:39
I can't see anything wrong with your config. Can you try a PA calibration print?

**Comment by deemax-real** [comment] 2024-11-09 18:51
Printer seems to ignore pressure advance setting and even command from console during printing. Can send photo of model printed with pa working and some model from today wit obvious overextruded corners. Even silly high pa value not change anything :)

**Comment by 3DCoded** [comment] 2024-11-09 19:01
Does the issue still occur if you comment out this line in your `printer.cfg`:

```
[include 3ms/main.cfg]
```

and add a test Dynamic Macro as explained [here](https://3dcoded.github.io/DynamicMacros/setup/#configuration)?

**Comment by deemax-real** [comment] 2024-11-09 19:19
PA and Smooth time coming back after commenting 3ms/main.cfg

but....
Dynamic Macros test done nothing. No response for MYTEST :/ 
![Screenshot_20241109_191219_com_android_chrome_ChromeTabbedActivity](https://github.com/user-attachments/assets/a9e8371b-9996-4392-9af8-ea1cc39ac7e4)
![Screenshot_20241109_191707_com_android_chrome_ChromeTabbedActivity](https://github.com/user-attachments/assets/ee8c90a5-f4a8-412b-98bf-df3949caeab0)

**Comment by deemax-real** [comment] 2024-11-09 19:48
After some tests I've find dynamic macros test didn't work with m117 command :/
After change in dynamic.cfg I'm getting response in console.
![Screenshot_20241109_194350_com_android_chrome_ChromeTabbedActivity](https://github.com/user-attachments/assets/d74a6f97-0b2f-48a5-a17e-584cb6b2dab1)
![Screenshot_20241109_194400_com_android_chrome_ChromeTabbedActivity](https://github.com/user-attachments/assets/a705a075-af20-4dd7-ac83-65307d5f10a3)

**Comment by 3DCoded** [comment] 2024-11-09 19:56
This is really confusing. Can you try the following steps and see if PA works?

1. Uncomment the `[include 3ms/main.cfg]` line in your `printer.cfg`
2. In `3ms/main.cfg`, comment out the `[dynamicmacros 3ms]` section.

Also, I would recommend replacing your main `[mcu]` configuration with a `/dev/serial/by-id` path (it's currently `/dev/ttyAMA0`), so it doesn't get confused with the 3MS board.

**Comment by deemax-real** [comment] 2024-11-09 20:09
After uncommenting 3ms/main.cfg PA gone from gui 

Pi connected by serial with printer mb so can't change to usb connection. Pi seen both mcu's without any problem and everything works (3ms motor spins and sync with main extruder motor) so don't think connection is a problem but later today or tomorrow I can try back to us connection for both mcu's.

**Comment by 3DCoded** [comment] 2024-11-09 20:36
> 2. In 3ms/main.cfg, comment out the [dynamicmacros 3ms] section.

Did you try this?

**Comment by deemax-real** [comment] 2024-11-09 20:37
Yes. No change

**Comment by 3DCoded** [comment] 2024-11-09 20:38
Ok. That helps to narrow down the issue. I'm guessing it has to do with how the `steppers.cfg` file is set up (probably my fault). I'll have to check this.

**Comment by deemax-real** [comment] 2024-11-09 20:39
Happy to try any solution :)

**Comment by 3DCoded** [comment] 2024-11-09 20:40
Hmm... That was the first configuration I used with the 3MS. I think it has to do with the serial port. I would recommend converting your serial to use `/dev/serial/by-id` for both the 3MS and your main MCU.

**Comment by deemax-real** [comment] 2024-11-09 20:46
Trying do this now but can't get 2 usb IDs from terminal. Don't know why.

**Comment by deemax-real** [comment] 2024-11-09 21:11
Usb sorted. 
Both mcu's connected by usb to pi
All changes/comments reverted.
No PA and Smooth time :(

![Screenshot_20241109_210604_com_android_chrome_ChromeTabbedActivity](https://github.com/user-attachments/assets/fbe90c8b-58cf-41e8-8db2-09e046699675)
![Screenshot_20241109_210529_com_android_chrome_ChromeTabbedActivity](https://github.com/user-attachments/assets/2c0e8c80-166c-492c-a05e-cedfeab478a6)
![Screenshot_20241109_210458_com_android_chrome_ChromeTabbedActivity](https://github.com/user-attachments/assets/2e0a050a-79ec-48f3-9024-fc8adbdd462e)

**Comment by 3DCoded** [comment] 2024-11-09 22:55
I think we're going to have to go through `3ms/main.cfg` and figure out what is causing the error. So far, it seems like the `steppers.cfg` is the issue. What happens if you comment out the `[include ./controllers/.../steppers.cfg]` line in `3ms/main.cfg`?

Thank you for your patience as we work through this error!

**Comment by deemax-real** [comment] 2024-11-09 23:17
After commenting steppers.cfg PA comes back. 
![Screenshot_20241109_231544_com_android_chrome_ChromeTabbedActivity](https://github.com/user-attachments/assets/61be468e-0a4d-4709-88f4-8e36c52885f6)

I'm happy to help (and desperate to find a solution) as I want my ender printing in colours for my sons :)

**Comment by 3DCoded** [comment] 2024-11-09 23:23
That helps to narrow down the issue. I have an idea:

In the `3ms/controllers/skr_mini_e3_v2/steppers.cfg`, can you comment out all the `extruder_stepper` sections?

If that doesn't work, can you try also commenting out the `[mcu 3ms]` section?

Let me know if either of those work (the 3MS won't work in this case but it should at least give another pointer to find the root cause).

**Comment by deemax-real** [comment] 2024-11-09 23:31
![Screenshot_20241109_232933_com_android_chrome_ChromeTabbedActivity](https://github.com/user-attachments/assets/271fdddc-ea2f-488c-b1a8-70e55f5210db)
![Screenshot_20241109_232833_com_android_chrome_ChromeTabbedActivity](https://github.com/user-attachments/assets/264da166-5cdc-471f-8386-96fccdfc6042)

**Comment by 3DCoded** [comment] 2024-11-11 11:25
Aside from updating Klipper, I don't really have other ideas. `extruder_stepper`s are part of standard Klipper, so I expected them to "just work" with any Klipper setup. If you can remove the 3MS configuration and add an `extruder_stepper` configuration, and PA still disappears, you might be able to get some help from the [Klipper Discourse](https://klipper.discourse.group/).

Alternatively, Happy Hare v3 beta just got released, which now supports the 3MS. It uses an entirely different configuration system, so if you want to become a beta tester, see #29.

**Comment by deemax-real** [comment] 2024-11-11 11:52
Hi, great news about Happy Hare beta. I'll lean into this way and we'll see if  PA working. 
Happy to be a beta tester.

**Comment by 3DCoded** [comment] 2024-11-15 14:19
Closing this issue as it's been moved to the HH Discord.

**Closed by 3DCoded** 2024-11-15 14:19 UTC
Labels: bug
